### ISSUE TITLE
Does jquery.appear has valid git tag ?

### ISSUE THREAD

**Issue by extend1994** [bas2k/jquery.appear#5]
Hi,
according to library request cdnjs/cdnjs#9525, I would like to check whether there is a valid tag allowing me to add the library with auto-update config which cdnjs will automatically updates libraries that are known to git repo.
For more details about auto-update config on cdnjs, you can check [this
](https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md)For more details about tag, maybe you can check https://git-scm.com/book/en/v2/Git-Basics-Tagging

Thank you!

**Comment by bas2k** [comment]
Hi, tag was added.

**Comment by extend1994** [comment]
Hi, thanks a lot for you work!
